name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # daily update
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          username: maheswari1829
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Update 3D graph"
          git push
